# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 228)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.ip_label.setObjectName("ip_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ip_label)
        self.ip_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip_lineEdit)
        self.port_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.port_label.setObjectName("port_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.port_label)
        self.port_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_lineEdit)
        self.user_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.user_label.setObjectName("user_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.user_label)
        self.user_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.user_lineEdit)
        self.password_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password_lineEdit)
        self.rtsp_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.rtsp_label.setObjectName("rtsp_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.rtsp_label)
        self.rtsp_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rtsp_lineEdit.setObjectName("rtsp_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rtsp_lineEdit)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ip_label.setText(_translate("Dialog", "ip"))
        self.port_label.setText(_translate("Dialog", "port"))
        self.user_label.setText(_translate("Dialog", "user"))
        self.password_label.setText(_translate("Dialog", "passwrod"))
        self.rtsp_label.setText(_translate("Dialog", "rtsp path"))
